# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Konjugate.Konjugate
PackageVersion: 1.1.5
InstallerLocale: en-US
InstallerType: nullsoft
Scope: machine
UpgradeBehavior: install
FileExtensions:
- kjt
ProductCode: com.konjugate
ReleaseDate: 2026-10-04
AppsAndFeaturesEntries:
- ProductCode: com.konjugate
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Konjugate'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/zenineasa/Konjugate/releases/download/v1.1.5/Konjugate-1.1.5-x64-setup.exe
  InstallerSha256: E540C7EF8EEB244D44DDF01B96C775D927370E8549B0328FAD6F9602A441615E
ManifestType: installer
ManifestVersion: 1.12.0
